-- Create "roles" table
CREATE TABLE "roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "permissions" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "roles_name_key" to table: "roles"
CREATE UNIQUE INDEX "roles_name_key" ON "roles" ("name");
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role_users" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "users_roles_users" FOREIGN KEY ("role_users") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "profiles" table
CREATE TABLE "profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "profile_picture" character varying NULL, "user_profile" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "profiles_users_profile" FOREIGN KEY ("user_profile") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "profiles_user_profile_key" to table: "profiles"
CREATE UNIQUE INDEX "profiles_user_profile_key" ON "profiles" ("user_profile");
