// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ali-Gorgani/chat-room-project/services/auth-service/utils/ent/auth"
	"github.com/Ali-Gorgani/chat-room-project/services/auth-service/utils/ent/predicate"
)

// AuthUpdate is the builder for updating Auth entities.
type AuthUpdate struct {
	config
	hooks    []Hook
	mutation *AuthMutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (au *AuthUpdate) Where(ps ...predicate.Auth) *AuthUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUserID sets the "user_id" field.
func (au *AuthUpdate) SetUserID(u uint) *AuthUpdate {
	au.mutation.ResetUserID()
	au.mutation.SetUserID(u)
	return au
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (au *AuthUpdate) SetNillableUserID(u *uint) *AuthUpdate {
	if u != nil {
		au.SetUserID(*u)
	}
	return au
}

// AddUserID adds u to the "user_id" field.
func (au *AuthUpdate) AddUserID(u int) *AuthUpdate {
	au.mutation.AddUserID(u)
	return au
}

// SetRefreshToken sets the "refresh_token" field.
func (au *AuthUpdate) SetRefreshToken(s string) *AuthUpdate {
	au.mutation.SetRefreshToken(s)
	return au
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (au *AuthUpdate) SetNillableRefreshToken(s *string) *AuthUpdate {
	if s != nil {
		au.SetRefreshToken(*s)
	}
	return au
}

// SetIsRevoked sets the "is_revoked" field.
func (au *AuthUpdate) SetIsRevoked(b bool) *AuthUpdate {
	au.mutation.SetIsRevoked(b)
	return au
}

// SetNillableIsRevoked sets the "is_revoked" field if the given value is not nil.
func (au *AuthUpdate) SetNillableIsRevoked(b *bool) *AuthUpdate {
	if b != nil {
		au.SetIsRevoked(*b)
	}
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *AuthUpdate) SetCreatedAt(t time.Time) *AuthUpdate {
	au.mutation.SetCreatedAt(t)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *AuthUpdate) SetNillableCreatedAt(t *time.Time) *AuthUpdate {
	if t != nil {
		au.SetCreatedAt(*t)
	}
	return au
}

// SetExpiresAt sets the "expires_at" field.
func (au *AuthUpdate) SetExpiresAt(t time.Time) *AuthUpdate {
	au.mutation.SetExpiresAt(t)
	return au
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (au *AuthUpdate) SetNillableExpiresAt(t *time.Time) *AuthUpdate {
	if t != nil {
		au.SetExpiresAt(*t)
	}
	return au
}

// Mutation returns the AuthMutation object of the builder.
func (au *AuthUpdate) Mutation() *AuthMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AuthUpdate) check() error {
	if v, ok := au.mutation.UserID(); ok {
		if err := auth.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Auth.user_id": %w`, err)}
		}
	}
	return nil
}

func (au *AuthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(auth.Table, auth.Columns, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UserID(); ok {
		_spec.SetField(auth.FieldUserID, field.TypeUint, value)
	}
	if value, ok := au.mutation.AddedUserID(); ok {
		_spec.AddField(auth.FieldUserID, field.TypeUint, value)
	}
	if value, ok := au.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := au.mutation.IsRevoked(); ok {
		_spec.SetField(auth.FieldIsRevoked, field.TypeBool, value)
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.SetField(auth.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.ExpiresAt(); ok {
		_spec.SetField(auth.FieldExpiresAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AuthUpdateOne is the builder for updating a single Auth entity.
type AuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthMutation
}

// SetUserID sets the "user_id" field.
func (auo *AuthUpdateOne) SetUserID(u uint) *AuthUpdateOne {
	auo.mutation.ResetUserID()
	auo.mutation.SetUserID(u)
	return auo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableUserID(u *uint) *AuthUpdateOne {
	if u != nil {
		auo.SetUserID(*u)
	}
	return auo
}

// AddUserID adds u to the "user_id" field.
func (auo *AuthUpdateOne) AddUserID(u int) *AuthUpdateOne {
	auo.mutation.AddUserID(u)
	return auo
}

// SetRefreshToken sets the "refresh_token" field.
func (auo *AuthUpdateOne) SetRefreshToken(s string) *AuthUpdateOne {
	auo.mutation.SetRefreshToken(s)
	return auo
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableRefreshToken(s *string) *AuthUpdateOne {
	if s != nil {
		auo.SetRefreshToken(*s)
	}
	return auo
}

// SetIsRevoked sets the "is_revoked" field.
func (auo *AuthUpdateOne) SetIsRevoked(b bool) *AuthUpdateOne {
	auo.mutation.SetIsRevoked(b)
	return auo
}

// SetNillableIsRevoked sets the "is_revoked" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableIsRevoked(b *bool) *AuthUpdateOne {
	if b != nil {
		auo.SetIsRevoked(*b)
	}
	return auo
}

// SetCreatedAt sets the "created_at" field.
func (auo *AuthUpdateOne) SetCreatedAt(t time.Time) *AuthUpdateOne {
	auo.mutation.SetCreatedAt(t)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableCreatedAt(t *time.Time) *AuthUpdateOne {
	if t != nil {
		auo.SetCreatedAt(*t)
	}
	return auo
}

// SetExpiresAt sets the "expires_at" field.
func (auo *AuthUpdateOne) SetExpiresAt(t time.Time) *AuthUpdateOne {
	auo.mutation.SetExpiresAt(t)
	return auo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableExpiresAt(t *time.Time) *AuthUpdateOne {
	if t != nil {
		auo.SetExpiresAt(*t)
	}
	return auo
}

// Mutation returns the AuthMutation object of the builder.
func (auo *AuthUpdateOne) Mutation() *AuthMutation {
	return auo.mutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (auo *AuthUpdateOne) Where(ps ...predicate.Auth) *AuthUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthUpdateOne) Select(field string, fields ...string) *AuthUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Auth entity.
func (auo *AuthUpdateOne) Save(ctx context.Context) (*Auth, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthUpdateOne) SaveX(ctx context.Context) *Auth {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AuthUpdateOne) check() error {
	if v, ok := auo.mutation.UserID(); ok {
		if err := auth.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Auth.user_id": %w`, err)}
		}
	}
	return nil
}

func (auo *AuthUpdateOne) sqlSave(ctx context.Context) (_node *Auth, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auth.Table, auth.Columns, sqlgraph.NewFieldSpec(auth.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Auth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auth.FieldID)
		for _, f := range fields {
			if !auth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UserID(); ok {
		_spec.SetField(auth.FieldUserID, field.TypeUint, value)
	}
	if value, ok := auo.mutation.AddedUserID(); ok {
		_spec.AddField(auth.FieldUserID, field.TypeUint, value)
	}
	if value, ok := auo.mutation.RefreshToken(); ok {
		_spec.SetField(auth.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := auo.mutation.IsRevoked(); ok {
		_spec.SetField(auth.FieldIsRevoked, field.TypeBool, value)
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.SetField(auth.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.ExpiresAt(); ok {
		_spec.SetField(auth.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &Auth{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
