// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ali-Gorgani/chat-room-project/services/auth-service/utils/ent/auth"
	"github.com/Ali-Gorgani/chat-room-project/services/auth-service/utils/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authFields := schema.Auth{}.Fields()
	_ = authFields
	// authDescUserID is the schema descriptor for user_id field.
	authDescUserID := authFields[1].Descriptor()
	// auth.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	auth.UserIDValidator = authDescUserID.Validators[0].(func(uint) error)
	// authDescIsRevoked is the schema descriptor for is_revoked field.
	authDescIsRevoked := authFields[3].Descriptor()
	// auth.DefaultIsRevoked holds the default value on creation for the is_revoked field.
	auth.DefaultIsRevoked = authDescIsRevoked.Default.(bool)
	// authDescCreatedAt is the schema descriptor for created_at field.
	authDescCreatedAt := authFields[4].Descriptor()
	// auth.DefaultCreatedAt holds the default value on creation for the created_at field.
	auth.DefaultCreatedAt = authDescCreatedAt.Default.(func() time.Time)
	// authDescID is the schema descriptor for id field.
	authDescID := authFields[0].Descriptor()
	// auth.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auth.IDValidator = authDescID.Validators[0].(func(string) error)
}
