server:
  port: 3002

grpc:
  user_host: "user-service"
  user_port: 8080
  auth_host: "auth-service"
  auth_port: 8081

postgres:
  host: "chat-db"
  port: "5432"
  user: "root"
  password: "secret"
  database: "chat-db"
  ssl_mode: "disable"
