basePath: /
host: localhost:3002
info:
  contact: {}
  description: API documentation for the Chat Room Chat Service
  title: Chat Room Chat API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: '"JWT Authorization header using the Bearer scheme. Example: \"Bearer
      {token}\""'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
